#!/usr/bin/python3

from   time    import time, sleep, localtime, strftime
import socket
import struct
import os
os.system('clear')

IP       = '192.168.0.11'
UDP_PORT = 61101

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind((IP, UDP_PORT))
#sock.listen(1)

def datetime() :
  return strftime("%Y-%m-%d %H:%M:%S :", localtime(time()))

print(datetime(), IP, UDP_PORT, 'udp_cmd is running')
while True:
  cmd, addr = sock.recvfrom(1024)
  sock.sendto(b'cmd OK :', addr)
  print(datetime())
  print(cmd)
  print(addr[0], addr[1])
  if b'close' in cmd : break
  os.system(cmd)

sock.close()
exit(0)

